Cubasells/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import login_required
# from project import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('project.urls','project'),'cubasells')),
    path("store/",include(('project.store.urls','store'),'store')),
    path("offer/",include(('project.offer.urls','offer'),'offer')),
    path("suboffer/",include(('project.suboffer.urls','suboffer'),'suboffer')),
    path("product/",include(('project.product.urls','product'),'product')),
    path('other/',include(('project.other.urls','other'),'other')),
    path('cart/',include(('project.cart.urls','cart'),'cart')),
    path('buy/',include(('project.buy.urls','buy'),'buy')),
    path('bank/',include(('project.bank.urls','bank'),'bank')),
    path('auction/',include(('project.auction.urls','auction'),'auction')),
    path('chat/',include(('project.chat.urls','chat'),'chat')),
    
]

project/store/urls.py
from django.urls import path,include
from django.urls import reverse_lazy
from django.contrib.auth.views import login_required

from project.store.views import *
from project.product.views import *
from project.offer.views import *
from project.suboffer.views import *
from project.auction.views import *

urlpatterns = [
    # Store
    path('',store_index,name='store_index'),
    path('list/',StoreListView.as_view(),name='store_list'),
    path('create/',login_required(StoreCreateView.as_view(),login_url=reverse_lazy('cubasells:login')),name='store_create'),
    path('<int:pk>/delete/',login_required(StoreDeleteView.as_view(),login_url=reverse_lazy('cubasells:login')),name='store_delete'),
    path('<int:pk>/update/',login_required(StoreUpdateView.as_view(),login_url=reverse_lazy('cubasells:login')),name='store_update'),
    path('<int:pk>/stats/', login_required(Graph.as_view(),login_url=reverse_lazy('cubasells:login')), name='store_stats'),

    path('<int:pk>/',StoreDetailView.as_view(),name='store_view'),
    

    path('<int:store_id>/product/',ProductListView.as_view(),name='store_product_list'),
    path('<int:store_id>/product/create/',login_required(ProductCreateView.as_view(),login_url=reverse_lazy('cubasells:login')),name='store_product_create'),

    path('<int:store_id>/offer/',OfferListView.as_view(),name='store_offer_list'),
    path('<int:store_id>/offer/adm_create/',login_required(OfferCreateView.as_view(),login_url=reverse_lazy('cubasells:login')),name='store_offer_create'),    

    path('<int:store_id>/suboffer/',login_required(SubOfferListView.as_view(),login_url=reverse_lazy('cubasells:login')),name='store_suboffer_list'),
    path('<int:store_id>/suboffer/adm_create/',login_required(SubOfferCreateView.as_view(),login_url=reverse_lazy('cubasells:login')),name='store_suboffer_create'),
    
    path('<int:store_id>/auction/',login_required(AuctionListView.as_view(),login_url=reverse_lazy('cubasells:login')),name='store_auction_list'),
    path('<int:store_id>/auction/create',login_required(AuctionCreateView.as_view(),login_url=reverse_lazy('cubasells:login')),name='store_auction_create'),
    # Test
    path('<int:store_id>/offer/create',login_required(StoreUserCreateView.as_view(),login_url=reverse_lazy('cubasells:login')),name='store_offer_create_user'),
    path('tags/', StoreTagFilterView.as_view(),name='store_tags_view'),
    
]

project/urls.py
from django.urls import path,include
from project.views import *
from django.urls import reverse_lazy
from django.contrib.auth.views import login_required

urlpatterns = [
    path('',index,name='index'),
    path('success/',success_view,name='success'),
    path('login/',MyLoginView.as_view(),name='login'),
    path('logout/',MyLogoutView.as_view(),name='logout'),

    # User
    path('user/',login_required(user_index,login_url=reverse_lazy('cubasells:login')),name='user_index'),
    path('user/create/',UserCreateView.as_view(),name='user_create'),
    path('user/<int:pk>/delete/',login_required(UserDeleteView.as_view(),login_url=reverse_lazy('cubasells:login')),name='user_delete'),
    path('user/<int:pk>/update/',login_required(UserUpdateView.as_view(),login_url=reverse_lazy('cubasells:login')),name='user_update'),
]

project/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
def validate_positive(number):
    if number < 0:
        raise ValidationError('%(number) must be a positive number',code='invalid number',params={'number':number,})

class Image(models.Model):
    
    name = models.CharField(name='ImageName',max_length=200)
    
    image = models.ImageField(name = 'Image', upload_to='images',default='default.jpg')
    
    owner = models.ForeignKey('project.MyUser', name="Owner", on_delete=models.CASCADE)

    def __str__(self):
        return self.ImageName

class Tag(models.Model):
    
    tag = models.CharField(name='Tag', max_length=50,unique=True)
    
    def __str__(self):
        return self.Tag

class MyUser(User):
     
    description = models.CharField(name="Description",max_length=400, default='',help_text='Description',blank=True)
    
    images = models.ManyToManyField(Image, name='Images',related_name='Images_User',blank=True)
    
    tags = models.ManyToManyField(Tag, name='Tags',related_name='Tags_User',blank=True)
    
    phone = models.PositiveIntegerField(name='Phone',null=True,blank=True)
    
    cart = models.OneToOneField('project.ShoppingCart',name='Cart',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.username
        
class BankAccount(models.Model):
    
    user = models.ForeignKey(MyUser,name = 'MyUser', on_delete=models.CASCADE)
    
    account = models.PositiveIntegerField(name='Account')
    
    class Meta:
        unique_together = ('MyUser','Account',)        
  
    def __str__(self):
        return f'{self.MyUser} {self.Account}'
    
class Store(models.Model):
    
    name = models.CharField(name='Name',max_length=150)
    
    create_date = models.DateTimeField(name="Create_Date",auto_now=False, auto_now_add=True)

    email = models.EmailField(name='Email', max_length=254)
    
    owner = models.ForeignKey(MyUser, name='Owner', on_delete=models.CASCADE)   
    
    description = models.CharField(name="Description",max_length=400, default='',help_text='Description',blank=True)
    
    images = models.ManyToManyField(Image, name='Images',related_name='Images_Store',blank=True)
    
    tags = models.ManyToManyField(Tag, name='Tags',related_name='Tags_Store',blank=True)
    
    phone = models.PositiveIntegerField(name='Phone',null=True,blank=True)
    
    bank_account = models.ForeignKey(BankAccount,name = 'Bank_Account', on_delete=models.CASCADE) 
    
    def __str__(self):
        return self.Name
    
class Product(models.Model):
    
    store_amount = models.PositiveIntegerField(name = "Store_Amount")
    
    store = models.ForeignKey(Store,name = 'Store',default=-1, on_delete=models.CASCADE)
    
    name = models.CharField(name='Name',max_length=150)
        
    description = models.CharField(name="Description",max_length=400, default='',help_text='Description',blank=True)
    
    images = models.ManyToManyField(Image, name='Images',related_name='Images_Product',blank=True)
    
    tags = models.ManyToManyField(Tag, name='Tags',related_name='Tags_Product',blank=True)
    
    def __str__(self):
        return f'{self.Name} in {self.Store.Name}'
    
class Chat(models.Model):
    
    sender_user = models.ForeignKey(MyUser, related_name='sender_table', on_delete=models.CASCADE)
    
    receiver_user = models.ForeignKey(MyUser,related_name='receiver_table', on_delete=models.CASCADE)
    
    date = models.DateTimeField(name='Date', auto_now=False, auto_now_add=True)
    
    message = models.CharField(name='Message', max_length=999)
    
    type_of_message = models.CharField(name='type',default='N',max_length=15,choices=[('N','Normal'),('I','Important'),('W','Warning')])
    
    def __str__(self):
        return f'{self.sender_user.username} -> {self.receiver_user.username}; {self.Date}'
    
class SubOffer(models.Model):
    
    product_offer = models.ForeignKey(Product, name = 'Product_offer',on_delete=models.CASCADE)
    
    amount = models.PositiveIntegerField(name='Amount')
    
    def __str__(self):
        return f'{self.Product_offer.Name}:{self.Amount}'

class Offer(models.Model):

    price = models.FloatField(name='Price',validators=(validate_positive,))
    
    name = models.CharField(name='Offer_name', max_length=50)
    
    description = models.CharField(name='Offer_description', max_length=150)
    
    store = models.ForeignKey(Store,name = 'Store', default = -1, on_delete=models.CASCADE)
    
    buy_offer = models.ManyToManyField(BankAccount,through='BuyOffer',through_fields=('Offer','Buyer'))
    
    images = models.ManyToManyField(Image, name='Images',related_name='Images_Offer',blank=True)
    
    tags = models.ManyToManyField(Tag, name='Tags',related_name='Tags_Offer',blank=True)

    suboffer = models.ManyToManyField(SubOffer,name='Suboffer',related_name='Suboffer_offer')
    
    def __str__(self):
        return f'{self.Offer_name}'

class BuyOffer(models.Model):
    
    buyer = models.ForeignKey(BankAccount, name='Buyer', on_delete=models.CASCADE)
    
    offer = models.ForeignKey(Offer,name='Offer', on_delete=models.CASCADE)
    
    buy_date = models.DateTimeField(name='Buy_Date', auto_now=False, auto_now_add=True)
    
    amount = models.PositiveIntegerField(name='Amount')
    
    def __str__(self):
        return f'{self.Buyer.MyUser.username} -> {self.Offer.Offer_name}; {self.Buy_Date}'
    
class Auction(models.Model):
    
    deposit_account = models.ForeignKey(BankAccount,name='Deposit',on_delete=models.CASCADE)
    
    winner = models.ForeignKey(BankAccount, name='Winner', related_name='winner',on_delete=models.CASCADE, blank=True,null=True)
    
    password = models.CharField(max_length=200,name='Password')
    
    offered = models.ForeignKey(Offer, name='Offered', on_delete=models.CASCADE)
    
    initial_date = models.DateTimeField(name='Initial_Date', auto_now=False, auto_now_add=False)
    
    final_date = models.DateTimeField(name='Final_Date', auto_now=False, auto_now_add=False)
    
    money_pool = models.PositiveIntegerField(name='Money')
    
    ended = models.BooleanField(name='Ended',default=False)
    
    status = models.CharField(name="Status",max_length=100,default='Not started')

    def __str__(self):
        return f'{self.Offered.Offer_name} {self.Money}'

class ShoppingCart(models.Model):
    pass    

class ShoppingOffer(models.Model):
    
    offer = models.ForeignKey(Offer,on_delete=models.CASCADE,name='Offer')
    
    amount = models.PositiveIntegerField(name='Amount')
    
    cart = models.ForeignKey(ShoppingCart, name='Cart', on_delete=models.CASCADE)

project/store/forms.py
from django import forms
from project.models import Store
from project.custom.forms import OrderForm

class MultiSelectSubOfferForm(forms.Form):

    def __init__(self, products,suboffers,*args, **kwargs):
        if products is None:
            products = []
        if suboffers is None:
            suboffers = []   
        setattr(self,'products',forms.ChoiceField(choices=[(x.id,x.Name) for x in products]))         
        setattr(self,'suboffers',forms.MultipleChoiceField(\
            choices=[((x.id,amount),x.Product_offer.Name + ' ' + str(amount)) for x,amount in suboffers]))         
        setattr(self,'amount',forms.IntegerField(min_value=1))         
        super(forms.Form, self).__init__(*args, **kwargs)
        self.fields['products'] = self.products
        self.fields['suboffers'] = self.suboffers
        self.fields['amount'] = self.amount


class StoreCreateForm(forms.ModelForm):
    success_url = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    class Meta:
        model = Store
        exclude=['Owner',]


class StoreOrderForm(OrderForm):
    model = Store
    fields_to_order = ['Name']

templates/store/create.html
{% extends "base/create.html" %}

{% block create_header %}
<h1 class="title-single">Create store</h1>
{% endblock create_header %}

{% block forms %}
{{form.as_p}}
{% if image_form %}
    {{ image_form.as_p }}
{% endif %}
{% endblock forms %}

{% block save %}
<button class="btn large">Save store</button>
{% endblock save %}

templates/store/index.html
{% extends "base/base.html" %} 

{% block header %}
<h1>Store Index</h1>
{% endblock header %} 

{% block body %}
<h1>Store Index Body</h1>

<li><a href="{% url 'store:store_list' %}">Store list</a></li>
<a href="{% url 'store:store_create' %}">Create store</a> 

{%endblock body%}

templates/store/list.html
{%extends 'base/list2.html' %}
{%load static%}

{%block btn%}
    <div class="container " style="margin-left: 150px;">
        <a class="btn large" href="{% url 'store:store_create'%}">Create store</a>
    </div>
    <br>
{%endblock btn%}

{%block search_collapse%}
<div class="click-closed"></div>
<!--/ Form Search Star /-->
<div class="box-collapse">
    <span class="close-box-collapse right-boxed ion-ios-close"></span>
    <div class="box-collapse-wrap form">
        <form class="form-a" method="post">
            {% csrf_token %}
            <div class="title-box-d">
                <h3 class="title-d">Search Store</h3>
            </div>
            <table>
                <br>
                {{filter.form.as_table}}
                <br>
            </table>
            <div class="title-box-d">
                <h3 class="title-d">Order Stores</h3>
            </div>
            <table>
                {{ order.as_table }}
            </table>
            <div class="title-box-d">
                <h3 class="title-d">Search for tags</h3>
            </div>
            {% if form1 %}
                <table>
                    {{form1.as_table}}
                </table>
            {% endif %}
            <input type="submit" value="Update and Export Data" name="export" class="col-md-12">
            <button class="btn btn-secondary col-md-12" type="submit">Update</button>
        </form>
    </div>

</div>
<!--/ Form Search End /-->
{%endblock search_collapse%}

{%block search%}
<button type="button" class="btn btn-search navbar-toggle-box-collapse d-none d-md-block" data-toggle="collapse"
    data-target="#navbarTogglerDemo01" aria-expanded="false" >
    <span class="fa fa-search" aria-hidden="false"></span>
</button>
{%endblock search%}

{%block url%}
<a  href="{% url 'store:store_view' object.id %}">{{object.Name}}</a>
{%endblock url%}


{%block add_features%}
<div class = "card-size-font">
    <p> {{object.Description}} </p>
    <p> Owner: {{object.Owner}}</p>
    {% ifequal object.Owner.id user.id %}
    <div class="btn-group top" style="justify-content: center; align-items: center;">
        <a class="btn btn-outline-primary" href="{% url 'store:store_update' object.id %}">Update</a>
        <a class="btn btn-outline-dark" href="{% url 'store:store_delete' object.id %}">Delete</a>
    </div>
    {% endifequal %}
</div>
{%endblock add_features%}

{%block else%}
<h1>No Stores</h1>
{%endblock else%}

{%block add_button%}

{%endblock add_button%}


<!-- {% block tag_filter_form %}
    
    {% if form1 %}
    <table> 
        {{form1.as_table}} 
    </table>
    {% endif %}
        
{% endblock tag_filter_form %}


{% block order_filter_forms %}
<table>
    {{ order.as_table }}
</table>
<table>
    {{filter.form.as_table}}
</table>
{% endblock order_filter_forms %} -->

templates/store/stats.html
{% extends "base/base.html" %} 

{% block header %}
<h1>Store Index</h1>
{% endblock header %} 


{% block body %}
{% ifequal user.id store.Owner.id %}
    <h2>
        <strong>Stats of: </strong>
        <a class="color-text-a" href="{% url 'store:store_view' store.id %}"> {{store.Name}}</a>
        <!-- <span class="color-text-a">{{object.Store.Name}} </span> -->
    </h2>
        {% if graph %}
            <div style="width:300;height:250">
            {{ graph|safe }}
            </div>
        {% endif %}
        {% if graph1 %}
            <div style="width:300;height:250">
            {{ graph1|safe }}
            </div>
        {% endif %}
{%else%}
    <h1>You are not allowed to see other user's store stats</h1>
{% endifequal %}

{%endblock body%}

templates/store/view.html
{% extends 'base/view.html' %}
{% load static %}

{% block first %}
<h1 class="title-single">Store</h1>
{% endblock first %}

{% block images %}
{% if store.Images.all %}
{% for img in store.Images.all %}
<li><img src="{% static img.Image.url %}" class="agent-avatar img-fluid" alt="Imagen"></li>
{% endfor %}
{% else %}
    <h2>No images</h2>
{% endif %}
{%endblock images%}

{%block init%}
    <h3 class="title-d">{{store.Name}} </h3>
{%endblock init%}


{% block descripcion %}
    {{store.Description}}
{% endblock descripcion %}

{%block features%}
<ul>
    {%if store.Tags.all%}
    <p>
        <strong>Tags:</strong>
    </p>
    {% for tag in store.Tags.all %}
    <li>{{tag.Tag}}</li>
    {% endfor %}
    {%else%}
    {%endif%}
</ul>
{%endblock features%}

{% block button%}
<div class="btn-group" style = "display:ruby-base-container;">
    <a class="btn btn-outline-success" href="{% url 'store:store_product_list' store.id %}">See Products</a>
    <a class="btn btn-outline-success" href="{% url 'store:store_offer_list' store.id %}">See Offers</a>
    {% ifequal user.id store.Owner.id %}
    <a class="btn btn-outline-success" href="{% url 'store:store_suboffer_list' store.id %}">See Suboffers</a>
    {%endifequal%}
    <a class="btn btn-outline-success" href="{% url 'store:store_auction_list' store.id %}">See Auctions</a>
</div>
<br>
<br>
{% ifequal user.id store.Owner.id %}
    <div class = "btn-group" style = "display:ruby-base-container;  " >
        <a class = "btn btn-outline-dark" href="{% url 'store:store_product_create' store.id %}">Add Product</a>
        <a class = "btn btn-outline-dark" href="{% url 'store:store_offer_create_user' store.id %}">Add Offer</a>
        <a class = "btn btn-outline-dark" href="{% url 'store:store_suboffer_create' store.id %}">Add Suboffer</a>
        <a class = "btn btn-outline-dark" href="{% url 'store:store_auction_create' object.id %}">Add Auction</a>  
    </div>
    <br>
    <br>
    <div class ="container" style = "padding-left: 40%">
        <div class="btn-group">
            <a class="btn btn-outline-success" href="{% url 'store:store_update' store.id %}">Update</a>
            <a class="btn btn-outline-dark" href="{% url 'store:store_delete' store.id %}">Delete</a>
            <a class="btn btn-outline-success" href="{% url 'store:store_stats' store.id %}">Stats</a>
        </div>
    </div>
{%endifequal%}
{% ifnotequal store.Owner.id user.id %}
    <div>
        <a class = "btn btn-outline-dark" href="{% url 'chat:chat_list' store.Owner.id %}"> Contact owner </a>
    </div>
{% endifnotequal %}
{% endblock button%}